import type { FoodItem, Total } from "@/types/globaltypes";


export const foodItems: FoodItem[] = [
  {
    id: "egg",
    name: "Egg (whole, raw, 100g)",
    macros: {
      calories: 143,
      protein_g: 12.6,
      fat_g: 9.5,
      carbs_g: 0.7,
    },
    micros: {
      sugar_g: 1.1,
      calcium_mg: 56,
      iron_mg: 1.75,
      magnesium_mg: 12,
      phosphorus_mg: 198,
      potassium_mg: 138,
      sodium_mg: 142,
      zinc_mg: 1.29,
      selenium_mcg: 30.7,
      vitamin_a_mcg: 160,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 2,
      vitamin_e_mg: 1.05,
      vitamin_b12_mcg: 0.89,
      folate_mcg: 47,
      choline_mg: 294,
    }
  },
  {
    id: "peanut",
    name: "Peanut (roasted, 100g)",
    macros: {
      calories: 567,
      protein_g: 25.8,
      fat_g: 49.2,
      carbs_g: 16.1,
    },
    micros: {
      fiber_g: 8.5,
      sugar_g: 4.7,
      calcium_mg: 92,
      iron_mg: 4.58,
      magnesium_mg: 168,
      phosphorus_mg: 376,
      potassium_mg: 705,
      sodium_mg: 18,
      zinc_mg: 3.3,
      copper_mg: 1.1,
      manganese_mg: 1.9,
      selenium_mcg: 7.2,
      vitamin_e_mg: 8.33,
      vitamin_b1_mg: 0.64,
      vitamin_b3_mg: 12,
      folate_mcg: 240,
    }
  },
  {
    id: "soya_chunks",
    name: "Soya Chunks (dry, 100g)",
    macros: {
      calories: 345,
      protein_g: 52,
      fat_g: 0.5,
      carbs_g: 33,
    },
    micros: {
      fiber_g: 13,
      sugar_g: 7, // Corrected from 33
      calcium_mg: 350,
      iron_mg: 20,
      magnesium_mg: 280,
      potassium_mg: 1800,
    }
  },
  {
    id: "paneer",
    name: "Paneer (100g)",
    macros: {
      calories: 298,
      protein_g: 18,
      fat_g: 22,
      carbs_g: 3.4,
    },
    micros: {
      sugar_g: 2.8,
      calcium_mg: 480,
      iron_mg: 0.5,
      phosphorus_mg: 208,
      sodium_mg: 22,
      vitamin_a_mcg: 210,
    }
  },
  {
    id: "milk",
    name: "Milk (cow, whole, 100g)",
    macros: {
      calories: 61,
      protein_g: 3.2,
      fat_g: 3.3,
      carbs_g: 4.8,
    },
    micros: {
      sugar_g: 4.8,
      calcium_mg: 113,
      iron_mg: 0.05,
      magnesium_mg: 10,
      phosphorus_mg: 95,
      potassium_mg: 138,
      sodium_mg: 49,
      zinc_mg: 0.37,
    }
  },
  {
    id: "roti",
    name: "Roti (whole wheat, 100g)",
    macros: {
      calories: 297,
      protein_g: 9.7,
      fat_g: 6.8,
      carbs_g: 51,
    },
    micros: {
      fiber_g: 7.1,
      sugar_g: 2.7,
      calcium_mg: 26,
      iron_mg: 2.7,
      magnesium_mg: 64,
      phosphorus_mg: 192,
      potassium_mg: 233,
      sodium_mg: 298,
      manganese_mg: 2.5,
      zinc_mg: 1.6,
    }
  },
  {
    id: "moong_daal",
    name: "Moong Daal (split, dry, 100g)",
    macros: {
      calories: 347,
      protein_g: 24,
      fat_g: 1,
      carbs_g: 59,
    },
    micros: {
      fiber_g: 8.2,
      iron_mg: 6.6,
      magnesium_mg: 97,
      potassium_mg: 1246,
    }
  },
  {
    id: "gram_flour",
    name: "Gram Flour (besan, 100g)",
    macros: {
      calories: 387,
      protein_g: 22,
      fat_g: 6,
      carbs_g: 58,
    },
    micros: {
      fiber_g: 10.8,
      calcium_mg: 45,
      iron_mg: 4.86,
      magnesium_mg: 166,
      phosphorus_mg: 318,
      potassium_mg: 846,
    }
  },
  {
    id: "black_chickpeas",
    name: "Black Chickpeas (dry, 100g)",
    macros: {
      calories: 364,
      protein_g: 20.5,
      fat_g: 5,
      carbs_g: 60,
    },
    micros: {
      fiber_g: 17,
      sugar_g: 11,
      potassium_mg: 877,
      calcium_mg: 143,
      iron_mg: 6.2,
      magnesium_mg: 166,
    }
  },
  {
    id: "soyabeans",
    name: "Soybeans (dry, 100g)",
    macros: {
      calories: 446,
      protein_g: 36.5,
      fat_g: 19.9,
      carbs_g: 30.2,
    },
    micros: {
      fiber_g: 9.3,
      calcium_mg: 277,
      iron_mg: 15.7,
      zinc_mg: 4.9,
      copper_mg: 1.65,
      manganese_mg: 2.5,
      phosphorus_mg: 704,
    }
  },
  {
    id: "oats",
    name: "Oats (rolled, 100g)",
    macros: {
      calories: 389,
      protein_g: 16.9,
      fat_g: 6.9,
      carbs_g: 66.3,
    },
    micros: {
      fiber_g: 10.6,
      iron_mg: 4.7,
      magnesium_mg: 177,
      phosphorus_mg: 523,
      potassium_mg: 429,
      zinc_mg: 3.97,
    }
  },
  {
    id: "almonds",
    name: "Almonds (100g)",
    macros: {
      calories: 579,
      protein_g: 21.2,
      fat_g: 49.9,
      carbs_g: 21.6,
    },
    micros: {
      fiber_g: 12.5,
      sugar_g: 4.4,
      calcium_mg: 269,
      iron_mg: 3.7,
      magnesium_mg: 270,
      phosphorus_mg: 481,
      potassium_mg: 733,
      sodium_mg: 1,
      zinc_mg: 3.1,
      copper_mg: 1,
      manganese_mg: 2.1,
      vitamin_e_mg: 25.6,
      riboflavin_mg: 1.14,
    }
  },
  {
    id: "walnuts",
    name: "Walnuts (100g)",
    macros: {
      calories: 654,
      protein_g: 15.2,
      fat_g: 65.2,
      carbs_g: 13.7,
    },
    micros: {
      fiber_g: 6.7,
      sugar_g: 2.6,
      calcium_mg: 98,
      iron_mg: 2.9,
      magnesium_mg: 158,
      phosphorus_mg: 346,
      potassium_mg: 441,
      sodium_mg: 2,
      zinc_mg: 3.1,
      copper_mg: 1.6,
      manganese_mg: 3.4,
      selenium_mcg: 4.9,
    }
  },
  {
    id: "curd",
    name: "Curd (plain, 100g)",
    macros: {
      calories: 61,
      protein_g: 3.5,
      fat_g: 3.3,
      carbs_g: 4.7,
    },
    micros: {
      sugar_g: 4.4,
      calcium_mg: 120,
      sodium_mg: 50,
    }
  },
  {
    id: "tofu",
    name: "Tofu (firm, 100g)",
    macros: {
      calories: 76,
      protein_g: 8.1,
      fat_g: 4.8,
      carbs_g: 1.9,
    },
    micros: {
      fiber_g: 0.3,
      calcium_mg: 350,
      iron_mg: 5.4,
      magnesium_mg: 30,
      phosphorus_mg: 97,
      potassium_mg: 121,
      sodium_mg: 7,
      zinc_mg: 1,
      copper_mg: 0.2,
      manganese_mg: 1,
      selenium_mcg: 9,
    }
  },
  {
    id: "chia",
    name: "Chia Seeds (100g)",
    macros: {
      calories: 486,
      protein_g: 16.5,
      fat_g: 30.7,
      carbs_g: 42.1,
    },
    micros: {
      fiber_g: 34.4,
      calcium_mg: 631,
      iron_mg: 7.7,
      magnesium_mg: 335,
      phosphorus_mg: 860,
      potassium_mg: 407,
      sodium_mg: 16,
      zinc_mg: 4.6,
      copper_mg: 0.9,
      manganese_mg: 2.7,
      selenium_mcg: 55,
      omega_3_g: 17.8,
    }
  },
  {
    id: "flax_seeds",
    name: "Flax Seeds (100g)",
    macros: {
      calories: 534,
      protein_g: 18.3,
      fat_g: 42.2,
      carbs_g: 28.9,
    },
    micros: {
      fiber_g: 27.3,
      sugar_g: 1.6,
      calcium_mg: 255,
      iron_mg: 5.7,
      magnesium_mg: 392,
      phosphorus_mg: 642,
      potassium_mg: 813,
      sodium_mg: 30,
      zinc_mg: 4.3,
      copper_mg: 1.3,
      manganese_mg: 2.5,
      selenium_mcg: 25.4,
      vitamin_b1_mg: 1.6,
    }
  },
  {
    id: "pumpkin_seeds",
    name: "Pumpkin Seeds (100g)",
    macros: {
      calories: 446,
      protein_g: 19,
      fat_g: 19,
      carbs_g: 54,
    },
    micros: {
      fiber_g: 18,
      calcium_mg: 55,
      iron_mg: 3.3,
      magnesium_mg: 262,
      phosphorus_mg: 92,
      potassium_mg: 919,
      sodium_mg: 18,
      zinc_mg: 10,
      copper_mg: 0.69,
      manganese_mg: 0.5,
    }
  },
  {
    id: "sunflower_seeds",
    name: "Sunflower Seeds (100g)",
    macros: {
      calories: 584,
      protein_g: 20.8,
      fat_g: 51.5,
      carbs_g: 20,
    },
    micros: {
      fiber_g: 8.6,
      sugar_g: 2.6,
      calcium_mg: 78,
      iron_mg: 5.3,
      magnesium_mg: 325,
      phosphorus_mg: 660,
      potassium_mg: 645,
      sodium_mg: 9,
      zinc_mg: 5,
      copper_mg: 1.8,
      manganese_mg: 2,
      selenium_mcg: 53,
      vitamin_e_mg: 35,
      vitamin_b1_mg: 1.5,
      vitamin_b6_mg: 1.3,
    }
  },
  {
    id: "hemp_seeds",
    name: "Hemp Seeds (100g)",
    macros: {
      calories: 553,
      protein_g: 31.6,
      fat_g: 48.8,
      carbs_g: 8.7,
    },
    micros: {
      fiber_g: 4,
      sugar_g: 1.5,
      calcium_mg: 70,
      iron_mg: 8,
      magnesium_mg: 700,
      phosphorus_mg: 1650,
      potassium_mg: 1200,
      sodium_mg: 5,
      zinc_mg: 9.9,
      copper_mg: 1.6,
      manganese_mg: 7.6,
      vitamin_b1_mg: 1.3,
      vitamin_b6_mg: 0.6,
    }
  },
  {
    id: "ghee",
    name: "Ghee (clarified butter, 100g)",
    macros: {
      calories: 876,
      protein_g: 0,
      fat_g: 99.8,
      carbs_g: 0,
    },
    micros: {
      monounsaturated_fat_g: 28.7,
      cholesterol_mg: 256,
      saturated_fat_g: 62.4,
      vitamin_a_mcg: 3069,
      polyunsaturated_fat_g: 3.7,
      vitamin_d_mcg: 1.3,
      vitamin_e_mg: 2.8,
      vitamin_k_mcg: 8.6,
    }
  },
  {
    id: "mustard_oil",
    name: "Mustard Oil (100g)",
    macros: {
      calories: 884,
      protein_g: 0,
      fat_g: 100,
      carbs_g: 0,
    },
    micros: {
      cholesterol_mg: 0,
      saturated_fat_g: 12,
      monounsaturated_fat_g: 59,
      polyunsaturated_fat_g: 21,
      vitamin_e_mg: 0.4,
    }
  },
  {
    id: "rice",
    name: "Rice (white, dry, 100g)",
    macros: {
      calories: 365,
      protein_g: 7.1,
      fat_g: 0.7,
      carbs_g: 80,
    },
    micros: {
      fiber_g: 1.3,
      sugar_g: 0.1,
      calcium_mg: 28,
      iron_mg: 1.2,
      magnesium_mg: 25,
      potassium_mg: 115,
    }
  },
  {
    id: "rajma",
    name: "Rajma (kidney beans, dry, 100g)",
    macros: {
      calories: 337,
      protein_g: 23,
      fat_g: 1.0,
      carbs_g: 61,
    },
    micros: {
      fiber_g: 15,
      sugar_g: 2,
      sodium_mg: 12,
      potassium_mg: 1359,
      calcium_mg: 83,
      iron_mg: 7,
      magnesium_mg: 138,
      phosphorus_mg: 406,
      zinc_mg: 3,
    }
  },
  {
    id: "chickpeas",
    name: "Chickpeas (dry, 100g)",
    macros: {
      calories: 378,
      protein_g: 20,
      fat_g: 6,
      carbs_g: 63,
    },
    micros: {
      fiber_g: 12,
      sugar_g: 11,
      calcium_mg: 57,
      iron_mg: 4.3,
      magnesium_mg: 79,
      phosphorus_mg: 252,
      potassium_mg: 718,
      sodium_mg: 24,
      zinc_mg: 2.8,
      copper_mg: 0.66,
      manganese_mg: 1.21,
      folate_mcg: 557,
    }
  },
  {
    id: "chicken",
    name: "Chicken Breast (cooked, 100g)",
    macros: {
      calories: 165,
      protein_g: 31,
      fat_g: 3.6,
      carbs_g: 0,
    },
    micros: {
      calcium_mg: 12,
      iron_mg: 1,
      magnesium_mg: 29,
      phosphorus_mg: 222,
      potassium_mg: 256,
      sodium_mg: 74,
      zinc_mg: 1,
      selenium_mcg: 22,
      niacin_mg: 14.8,
      vitamin_b6_mg: 0.6,
      vitamin_b12_mcg: 0.3,
      choline_mg: 85,
    }
  },
  {
    id: "apple",
    name: "Apple (raw, 100g)",
    macros: {
      calories: 52,
      protein_g: 0.3,
      fat_g: 0.2,
      carbs_g: 14,
    },
    micros: {
      fiber_g: 2.4,
      sugar_g: 10,
      calcium_mg: 6,
      iron_mg: 0.1,
      magnesium_mg: 5,
      phosphorus_mg: 11,
      potassium_mg: 107,
      sodium_mg: 1,
      zinc_mg: 0.04,
      vitamin_c_mg: 4.6,
      vitamin_b6_mg: 0.04,
    }
  },
  {
    id: "banana",
    name: "Banana (raw, 100g)",
    macros: {
      calories: 89,
      protein_g: 1.1,
      fat_g: 0.3,
      carbs_g: 23,
    },
    micros: {
      fiber_g: 2.6,
      sugar_g: 12,
      calcium_mg: 5,
      iron_mg: 0.3,
      magnesium_mg: 27,
      phosphorus_mg: 22,
      potassium_mg: 358,
      sodium_mg: 1,
      zinc_mg: 0.15,
      vitamin_b6_mg: 0.37,
      vitamin_c_mg: 8.7,
      manganese_mg: 0.27,
    }
  },
  {
    id: "cashews",
    name: "Cashews (dry, 100g)",
    macros: {
      calories: 553,
      protein_g: 18.2,
      fat_g: 43.8,
      carbs_g: 30.2,
    },
    micros: {
      fiber_g: 3.3,
      calcium_mg: 37,
      iron_mg: 6.68,
    }
  },
  {
    id: "raisins",
    name: "Raisins (100g)",
    macros: {
      calories: 299,
      protein_g: 3.1,
      fat_g: 0.5,
      carbs_g: 79,
    },
    micros: {
      fiber_g: 3.7,
      sugar_g: 59,
      calcium_mg: 50,
      iron_mg: 1.9,
      magnesium_mg: 32,
      phosphorus_mg: 101,
      potassium_mg: 749,
      sodium_mg: 11,
      zinc_mg: 0.22,
      copper_mg: 0.32,
      manganese_mg: 0.3,
    }
  },
  {
    id: "spinach",
    name: "Spinach (raw, 100g)",
    macros: {
      calories: 23,
      protein_g: 2.9,
      fat_g: 0.4,
      carbs_g: 3.6,
    },
    micros: {
      fiber_g: 2.2,
      sugar_g: 0.4,
      calcium_mg: 99,
      iron_mg: 2.7,
      magnesium_mg: 79,
      potassium_mg: 558,
      sodium_mg: 79,
      zinc_mg: 0.5,
      folate_mcg: 194,
      vitamin_a_mcg: 469,
      vitamin_c_mg: 28.1,
      vitamin_k_mcg: 482.9,
    }
  },
  {
    id: "amla",
    name: "Amla (Indian gooseberry, raw, 100g)",
    macros: {
      calories: 44,
      protein_g: 0.9,
      carbs_g: 10.2,
      fat_g: 0.6,
    },
    micros: {
      calcium_mg: 25,
      iron_mg: 0.9,
      sugar_g: 4.4,
      magnesium_mg: 10,
      fiber_g: 4.3,
      phosphorus_mg: 21,
      potassium_mg: 198,
      sodium_mg: 13,
      copper_mg: 0.1,
      manganese_mg: 0.1,
      zinc_mg: 0.12,
      selenium_mcg: 0.6,
      vitamin_a_mcg: 31,
      vitamin_c_mg: 478,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.16,
      vitamin_k_mcg: 1.6,
      vitamin_b1_mg: 0.04,
      vitamin_b2_mg: 0.03,
      niacin_mg: 0.3,
      vitamin_b5_mg: 0.25,
      vitamin_b6_mg: 0.06,
      vitamin_b9_mcg: 6,
      choline_mg: 4,
      cholesterol_mg: 0,
      omega_3_g: 0.048,
    }
  }
  // Add more foods as needed per above reference/corrections.
];



export const dailyRequirements :Total= {
  macros: {
    calories: 2000,
    protein_g: 50,
    carbs_g: 275,
    fat_g: 70,
  },
  micros: {
    calcium_mg: 1000,
  iron_mg: 18,
  zinc_mg: 11,
  magnesium_mg: 400,
  phosphorus_mg: 700,
  potassium_mg: 4700,
  sodium_mg: 1500,
  copper_mg: 0.9,
  manganese_mg: 2.3,

  fiber_g: 28,
  sugar_g: 25, 
  saturated_fat_g: 20, 
  monounsaturated_fat_g: 30, 
  polyunsaturated_fat_g: 17, 
  omega_3_g: 1.6, 

  selenium_mcg: 55,
  vitamin_a_mcg: 900,
  vitamin_a_iu: 3000, 

  vitamin_c_mg: 90,
  vitamin_d_mcg: 15,
  vitamin_e_mg: 15,
  vitamin_k_mcg: 120,

  vitamin_b1_mg: 1.2,
  vitamin_b2_mg: 1.3,
  riboflavin_mg: 1.3, 
  vitamin_b3_mg: 16,
  niacin_mg: 16, 
  vitamin_b5_mg: 5,
  vitamin_b6_mg: 1.3,
  vitamin_b7_mcg: 30, 
  vitamin_b9_mcg: 400,
  folate_mcg: 400, 
  vitamin_b12_mcg: 2.4,

  choline_mg: 550,
  cholesterol_mg: 300
  }
} as const;
