import type { FoodItem, Total } from "@/types/globaltypes";

export const foodItems: FoodItem[] = [
  {
    id: "egg",
    name: "Egg (whole, raw, 100g)",
    macros: {
      calories: 143,
      protein_g: 12.6,
      fat_g: 9.5,
      carbs_g: 0.7,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 1.1,
      calcium_mg: 56,
      iron_mg: 1.75,
      magnesium_mg: 12,
      phosphorus_mg: 198,
      potassium_mg: 138,
      sodium_mg: 142,
      zinc_mg: 1.29,
      copper_mg: 0.08,
      manganese_mg: 0.03,
      selenium_mcg: 30.7,
      iodine_mcg: 48,
      saturated_fat_g: 3.1,
      monounsaturated_fat_g: 3.6,
      polyunsaturated_fat_g: 1.9,
      omega_3_g: 0.11,
      omega_6_g: 1.8,
      vitamin_a_mcg: 160,
      vitamin_b1_mg: 0.05,
      vitamin_b2_mg: 0.51,
      vitamin_b3_mg: 0.06,
      vitamin_b5_mg: 1.4,
      vitamin_b6_mg: 0.12,
      biotin_mcg: 10,
      folate_mcg: 47,
      vitamin_b12_mcg: 0.89,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 2,
      vitamin_e_mg: 1.05,
      vitamin_k_mcg: 0.3,
      choline_mg: 294,
      cholesterol_mg: 372,
    },
  },
  {
    id: "peanut",
    name: "Peanut (roasted, 100g)",
    macros: {
      calories: 567,
      protein_g: 25.8,
      fat_g: 49.2,
      carbs_g: 16.1,
    },
    micros: {
      fiber_g: 8.5,
      sugar_g: 4.7,
      calcium_mg: 92,
      iron_mg: 4.58,
      magnesium_mg: 168,
      phosphorus_mg: 376,
      potassium_mg: 705,
      sodium_mg: 18,
      zinc_mg: 3.3,
      copper_mg: 1.1,
      manganese_mg: 1.9,
      selenium_mcg: 7.2,
      iodine_mcg: 3,
      saturated_fat_g: 6.9,
      monounsaturated_fat_g: 24.4,
      polyunsaturated_fat_g: 15.6,
      omega_3_g: 0.01,
      omega_6_g: 15.5,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.64,
      vitamin_b2_mg: 0.14,
      vitamin_b3_mg: 12,
      vitamin_b5_mg: 1.7,
      vitamin_b6_mg: 0.35,
      biotin_mcg: 25,
      folate_mcg: 240,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 8.33,
      vitamin_k_mcg: 0,
      choline_mg: 52,
      cholesterol_mg: 0,
    },
  },
  {
    id: "soya_chunks",
    name: "Soya Chunks (dry, 100g)",
    macros: {
      calories: 345,
      protein_g: 52,
      fat_g: 0.5,
      carbs_g: 33,
    },
    micros: {
      fiber_g: 13,
      sugar_g: 7,
      calcium_mg: 350,
      iron_mg: 20,
      magnesium_mg: 280,
      phosphorus_mg: 705,
      potassium_mg: 1800,
      sodium_mg: 75,
      zinc_mg: 4.9,
      copper_mg: 1.3,
      manganese_mg: 2.2,
      selenium_mcg: 8,
      iodine_mcg: 8,
      saturated_fat_g: 0.1,
      monounsaturated_fat_g: 0.1,
      polyunsaturated_fat_g: 0.3,
      omega_3_g: 0.14,
      omega_6_g: 0.3,
      vitamin_a_mcg: 9,
      vitamin_b1_mg: 0.5,
      vitamin_b2_mg: 0.2,
      vitamin_b3_mg: 1.8,
      vitamin_b5_mg: 0.2,
      vitamin_b6_mg: 0.35,
      biotin_mcg: 60,
      folate_mcg: 375,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 1.5,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.8,
      vitamin_k_mcg: 0,
      choline_mg: 116,
      cholesterol_mg: 0,
    },
  },
  {
    id: "paneer",
    name: "Paneer (100g)",
    macros: {
      calories: 298,
      protein_g: 18,
      fat_g: 22,
      carbs_g: 3.4,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 2.8,
      calcium_mg: 480,
      iron_mg: 0.5,
      magnesium_mg: 20,
      phosphorus_mg: 208,
      potassium_mg: 98,
      sodium_mg: 22,
      zinc_mg: 2.3,
      copper_mg: 0.03,
      manganese_mg: 0.01,
      selenium_mcg: 15,
      iodine_mcg: 32,
      saturated_fat_g: 14.3,
      monounsaturated_fat_g: 6.3,
      polyunsaturated_fat_g: 0.6,
      omega_3_g: 0.05,
      omega_6_g: 0.5,
      vitamin_a_mcg: 210,
      vitamin_b1_mg: 0.03,
      vitamin_b2_mg: 0.26,
      vitamin_b3_mg: 0.2,
      vitamin_b5_mg: 0.1,
      vitamin_b6_mg: 0.09,
      biotin_mcg: 2,
      folate_mcg: 17,
      vitamin_b12_mcg: 0.6,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0.5,
      vitamin_e_mg: 0.2,
      vitamin_k_mcg: 2.4,
      choline_mg: 15,
      cholesterol_mg: 91,
    },
  },
  {
    id: "milk",
    name: "Milk (cow, whole, 100g)",
    macros: {
      calories: 61,
      protein_g: 3.2,
      fat_g: 3.3,
      carbs_g: 4.8,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 4.8,
      calcium_mg: 113,
      iron_mg: 0.05,
      magnesium_mg: 10,
      phosphorus_mg: 95,
      potassium_mg: 138,
      sodium_mg: 49,
      zinc_mg: 0.37,
      copper_mg: 0.01,
      manganese_mg: 0.003,
      selenium_mcg: 3.7,
      iodine_mcg: 45,
      saturated_fat_g: 2.1,
      monounsaturated_fat_g: 0.8,
      polyunsaturated_fat_g: 0.2,
      omega_3_g: 0.04,
      omega_6_g: 0.1,
      vitamin_a_mcg: 32,
      vitamin_b1_mg: 0.03,
      vitamin_b2_mg: 0.16,
      vitamin_b3_mg: 0.08,
      vitamin_b5_mg: 0.3,
      vitamin_b6_mg: 0.05,
      biotin_mcg: 2,
      folate_mcg: 5,
      vitamin_b12_mcg: 0.36,
      vitamin_c_mg: 1,
      vitamin_d_mcg: 1.3,
      vitamin_e_mg: 0.07,
      vitamin_k_mcg: 0.3,
      choline_mg: 24,
      cholesterol_mg: 14,
    },
  },
  {
    id: "roti",
    name: "Roti (whole wheat, 100g)",
    macros: {
      calories: 297,
      protein_g: 9.7,
      fat_g: 6.8,
      carbs_g: 51,
    },
    micros: {
      fiber_g: 7.1,
      sugar_g: 2.7,
      calcium_mg: 26,
      iron_mg: 2.7,
      magnesium_mg: 64,
      phosphorus_mg: 192,
      potassium_mg: 233,
      sodium_mg: 298,
      zinc_mg: 1.6,
      copper_mg: 0.19,
      manganese_mg: 2.5,
      selenium_mcg: 37,
      iodine_mcg: 4,
      saturated_fat_g: 1.2,
      monounsaturated_fat_g: 1.1,
      polyunsaturated_fat_g: 3.3,
      omega_3_g: 0.07,
      omega_6_g: 3.2,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.38,
      vitamin_b2_mg: 0.1,
      vitamin_b3_mg: 5.5,
      vitamin_b5_mg: 0.8,
      vitamin_b6_mg: 0.3,
      biotin_mcg: 6,
      folate_mcg: 44,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.3,
      vitamin_k_mcg: 1.3,
      choline_mg: 12,
      cholesterol_mg: 0,
    },
  },
  {
    id: "moong_daal",
    name: "Moong Daal (split, dry, 100g)",
    macros: {
      calories: 347,
      protein_g: 24,
      fat_g: 1,
      carbs_g: 59,
    },
    micros: {
      fiber_g: 8.2,
      sugar_g: 2,
      calcium_mg: 132,
      iron_mg: 6.6,
      magnesium_mg: 97,
      phosphorus_mg: 300,
      potassium_mg: 1246,
      sodium_mg: 14,
      zinc_mg: 2.7,
      copper_mg: 0.85,
      manganese_mg: 1.0,
      selenium_mcg: 3,
      iodine_mcg: 5,
      saturated_fat_g: 0.2,
      monounsaturated_fat_g: 0.2,
      polyunsaturated_fat_g: 0.4,
      omega_3_g: 0.02,
      omega_6_g: 0.3,
      vitamin_a_mcg: 1,
      vitamin_b1_mg: 0.64,
      vitamin_b2_mg: 0.16,
      vitamin_b3_mg: 2.25,
      vitamin_b5_mg: 2.0,
      vitamin_b6_mg: 0.3,
      biotin_mcg: 43,
      folate_mcg: 625,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 1.5,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.5,
      vitamin_k_mcg: 0,
      choline_mg: 30,
      cholesterol_mg: 0,
    },
  },
  {
    id: "gram_flour",
    name: "Gram Flour (besan, 100g)",
    macros: {
      calories: 387,
      protein_g: 22,
      fat_g: 6,
      carbs_g: 58,
    },
    micros: {
      fiber_g: 10.8,
      sugar_g: 11,
      calcium_mg: 45,
      iron_mg: 4.86,
      magnesium_mg: 166,
      phosphorus_mg: 318,
      potassium_mg: 846,
      sodium_mg: 42,
      zinc_mg: 2.7,
      copper_mg: 0.73,
      manganese_mg: 1.8,
      selenium_mcg: 2,
      iodine_mcg: 4,
      saturated_fat_g: 0.9,
      monounsaturated_fat_g: 1.3,
      polyunsaturated_fat_g: 2.7,
      omega_3_g: 0.05,
      omega_6_g: 2.6,
      vitamin_a_mcg: 8,
      vitamin_b1_mg: 0.5,
      vitamin_b2_mg: 0.15,
      vitamin_b3_mg: 3.2,
      vitamin_b5_mg: 1.2,
      vitamin_b6_mg: 0.32,
      biotin_mcg: 48,
      folate_mcg: 557,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.3,
      vitamin_k_mcg: 0,
      choline_mg: 46,
      cholesterol_mg: 0,
    },
  },
  {
    id: "black_chickpeas",
    name: "Black Chickpeas (dry, 100g)",
    macros: {
      calories: 364,
      protein_g: 20.5,
      fat_g: 5,
      carbs_g: 60,
    },
    micros: {
      fiber_g: 17,
      sugar_g: 11,
      calcium_mg: 143,
      iron_mg: 6.2,
      magnesium_mg: 166,
      phosphorus_mg: 367,
      potassium_mg: 877,
      sodium_mg: 29,
      zinc_mg: 2.7,
      copper_mg: 0.7,
      manganese_mg: 1.7,
      selenium_mcg: 8,
      iodine_mcg: 6,
      saturated_fat_g: 0.5,
      monounsaturated_fat_g: 1.2,
      polyunsaturated_fat_g: 2.1,
      omega_3_g: 0.08,
      omega_6_g: 2.0,
      vitamin_a_mcg: 17,
      vitamin_b1_mg: 0.48,
      vitamin_b2_mg: 0.15,
      vitamin_b3_mg: 2.5,
      vitamin_b5_mg: 1.3,
      vitamin_b6_mg: 0.29,
      biotin_mcg: 35,
      folate_mcg: 557,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 4,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.6,
      vitamin_k_mcg: 0,
      choline_mg: 28,
      cholesterol_mg: 0,
    },
  },
  {
    id: "soyabeans",
    name: "Soybeans (dry, 100g)",
    macros: {
      calories: 446,
      protein_g: 36.5,
      fat_g: 19.9,
      carbs_g: 30.2,
    },
    micros: {
      fiber_g: 9.3,
      sugar_g: 3,
      calcium_mg: 277,
      iron_mg: 15.7,
      magnesium_mg: 280,
      phosphorus_mg: 704,
      potassium_mg: 1797,
      sodium_mg: 86,
      zinc_mg: 4.9,
      copper_mg: 1.65,
      manganese_mg: 2.5,
      selenium_mcg: 53,
      iodine_mcg: 7,
      saturated_fat_g: 2.9,
      monounsaturated_fat_g: 4.4,
      polyunsaturated_fat_g: 11.3,
      omega_3_g: 1.5,
      omega_6_g: 9.5,
      vitamin_a_mcg: 5,
      vitamin_b1_mg: 0.87,
      vitamin_b2_mg: 0.27,
      vitamin_b3_mg: 1.6,
      vitamin_b5_mg: 0.8,
      vitamin_b6_mg: 0.38,
      biotin_mcg: 60,
      folate_mcg: 375,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 6.3,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 27.3,
      vitamin_k_mcg: 47,
      choline_mg: 155,
      cholesterol_mg: 0,
    },
  },
  {
    id: "oats",
    name: "Oats (rolled, 100g)",
    macros: {
      calories: 389,
      protein_g: 16.9,
      fat_g: 6.9,
      carbs_g: 66.3,
    },
    micros: {
      fiber_g: 10.6,
      sugar_g: 0,
      calcium_mg: 54,
      iron_mg: 4.7,
      magnesium_mg: 177,
      phosphorus_mg: 523,
      potassium_mg: 429,
      sodium_mg: 2,
      zinc_mg: 3.97,
      copper_mg: 0.6,
      manganese_mg: 4.9,
      selenium_mcg: 56,
      iodine_mcg: 4,
      saturated_fat_g: 1.2,
      monounsaturated_fat_g: 2.2,
      polyunsaturated_fat_g: 2.5,
      omega_3_g: 0.1,
      omega_6_g: 2.3,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.76,
      vitamin_b2_mg: 0.15,
      vitamin_b3_mg: 0.96,
      vitamin_b5_mg: 1.35,
      vitamin_b6_mg: 0.12,
      biotin_mcg: 22,
      folate_mcg: 56,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.72,
      vitamin_k_mcg: 1.9,
      choline_mg: 40,
      cholesterol_mg: 0,
    },
  },
  {
    id: "almonds",
    name: "Almonds (100g)",
    macros: {
      calories: 579,
      protein_g: 21.2,
      fat_g: 49.9,
      carbs_g: 21.6,
    },
    micros: {
      fiber_g: 12.5,
      sugar_g: 4.4,
      calcium_mg: 269,
      iron_mg: 3.7,
      magnesium_mg: 270,
      phosphorus_mg: 481,
      potassium_mg: 733,
      sodium_mg: 1,
      zinc_mg: 3.1,
      copper_mg: 1,
      manganese_mg: 2.1,
      selenium_mcg: 50,
      iodine_mcg: 2,
      saturated_fat_g: 3.8,
      monounsaturated_fat_g: 31.6,
      polyunsaturated_fat_g: 12.3,
      omega_3_g: 0.04,
      omega_6_g: 12.3,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.2,
      vitamin_b2_mg: 1.14,
      vitamin_b3_mg: 3.6,
      vitamin_b5_mg: 0.5,
      vitamin_b6_mg: 0.14,
      biotin_mcg: 44,
      folate_mcg: 44,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 25.6,
      vitamin_k_mcg: 0,
      choline_mg: 52,
      cholesterol_mg: 0,
    },
  },
  {
    id: "walnuts",
    name: "Walnuts (100g)",
    macros: {
      calories: 654,
      protein_g: 15.2,
      fat_g: 65.2,
      carbs_g: 13.7,
    },
    micros: {
      fiber_g: 6.7,
      sugar_g: 2.6,
      calcium_mg: 98,
      iron_mg: 2.9,
      magnesium_mg: 158,
      phosphorus_mg: 346,
      potassium_mg: 441,
      sodium_mg: 2,
      zinc_mg: 3.1,
      copper_mg: 1.6,
      manganese_mg: 3.4,
      selenium_mcg: 4.9,
      iodine_mcg: 1,
      saturated_fat_g: 6.3,
      monounsaturated_fat_g: 8.9,
      polyunsaturated_fat_g: 47.2,
      omega_3_g: 9.1,
      omega_6_g: 38.1,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.34,
      vitamin_b2_mg: 0.15,
      vitamin_b3_mg: 1.1,
      vitamin_b5_mg: 0.6,
      vitamin_b6_mg: 0.54,
      biotin_mcg: 1.7,
      folate_mcg: 98,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 1.3,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.7,
      vitamin_k_mcg: 2.7,
      choline_mg: 39,
      cholesterol_mg: 0,
    },
  },
  {
    id: "curd",
    name: "Curd (plain, 100g)",
    macros: {
      calories: 61,
      protein_g: 3.5,
      fat_g: 3.3,
      carbs_g: 4.7,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 4.4,
      calcium_mg: 120,
      iron_mg: 0.1,
      magnesium_mg: 12,
      phosphorus_mg: 95,
      potassium_mg: 155,
      sodium_mg: 50,
      zinc_mg: 0.6,
      copper_mg: 0.01,
      manganese_mg: 0.003,
      selenium_mcg: 4,
      iodine_mcg: 32,
      saturated_fat_g: 2.1,
      monounsaturated_fat_g: 0.8,
      polyunsaturated_fat_g: 0.2,
      omega_3_g: 0.04,
      omega_6_g: 0.1,
      vitamin_a_mcg: 32,
      vitamin_b1_mg: 0.02,
      vitamin_b2_mg: 0.16,
      vitamin_b3_mg: 0.08,
      vitamin_b5_mg: 0.3,
      vitamin_b6_mg: 0.05,
      biotin_mcg: 2,
      folate_mcg: 5,
      vitamin_b12_mcg: 0.36,
      vitamin_c_mg: 0.5,
      vitamin_d_mcg: 0.4,
      vitamin_e_mg: 0.05,
      vitamin_k_mcg: 0.2,
      choline_mg: 15,
      cholesterol_mg: 10,
    },
  },
  {
    id: "tofu",
    name: "Tofu (firm, 100g)",
    macros: {
      calories: 76,
      protein_g: 8.1,
      fat_g: 4.8,
      carbs_g: 1.9,
    },
    micros: {
      fiber_g: 0.3,
      sugar_g: 0.2,
      calcium_mg: 350,
      iron_mg: 5.4,
      magnesium_mg: 30,
      phosphorus_mg: 97,
      potassium_mg: 121,
      sodium_mg: 7,
      zinc_mg: 1,
      copper_mg: 0.2,
      manganese_mg: 1,
      selenium_mcg: 9,
      iodine_mcg: 12,
      saturated_fat_g: 0.7,
      monounsaturated_fat_g: 1.0,
      polyunsaturated_fat_g: 2.7,
      omega_3_g: 0.14,
      omega_6_g: 2.5,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.1,
      vitamin_b2_mg: 0.06,
      vitamin_b3_mg: 0.4,
      vitamin_b5_mg: 0.1,
      vitamin_b6_mg: 0.06,
      biotin_mcg: 9,
      folate_mcg: 23,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0.1,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.01,
      vitamin_k_mcg: 2.8,
      choline_mg: 15,
      cholesterol_mg: 0,
    },
  },
  {
    id: "chia",
    name: "Chia Seeds (100g)",
    macros: {
      calories: 486,
      protein_g: 16.5,
      fat_g: 30.7,
      carbs_g: 42.1,
    },
    micros: {
      fiber_g: 34.4,
      sugar_g: 0,
      calcium_mg: 631,
      iron_mg: 7.7,
      magnesium_mg: 335,
      phosphorus_mg: 860,
      potassium_mg: 407,
      sodium_mg: 16,
      zinc_mg: 4.6,
      copper_mg: 0.9,
      manganese_mg: 2.7,
      selenium_mcg: 55,
      iodine_mcg: 10,
      saturated_fat_g: 3.3,
      monounsaturated_fat_g: 2.3,
      polyunsaturated_fat_g: 23.7,
      omega_3_g: 17.8,
      omega_6_g: 5.8,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.62,
      vitamin_b2_mg: 0.26,
      vitamin_b3_mg: 2.3,
      vitamin_b5_mg: 0.9,
      vitamin_b6_mg: 0.17,
      biotin_mcg: 23,
      folate_mcg: 78,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 1.3,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.5,
      vitamin_k_mcg: 0,
      choline_mg: 98,
      cholesterol_mg: 0,
    },
  },
  {
    id: "flax",
    name: "Flax Seeds (100g)",
    macros: {
      calories: 534,
      protein_g: 18.3,
      fat_g: 42.2,
      carbs_g: 28.9,
    },
    micros: {
      fiber_g: 27.3,
      sugar_g: 1.6,
      calcium_mg: 255,
      iron_mg: 5.7,
      magnesium_mg: 392,
      phosphorus_mg: 642,
      potassium_mg: 813,
      sodium_mg: 30,
      zinc_mg: 4.3,
      copper_mg: 1.3,
      manganese_mg: 2.5,
      selenium_mcg: 25.4,
      iodine_mcg: 8,
      saturated_fat_g: 3.7,
      monounsaturated_fat_g: 7.7,
      polyunsaturated_fat_g: 28.7,
      omega_3_g: 22.8,
      omega_6_g: 5.9,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 1.6,
      vitamin_b2_mg: 0.16,
      vitamin_b3_mg: 3.1,
      vitamin_b5_mg: 0.48,
      vitamin_b6_mg: 0.47,
      biotin_mcg: 76,
      folate_mcg: 87,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0.6,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.31,
      vitamin_k_mcg: 4.3,
      choline_mg: 78,
      cholesterol_mg: 0,
    },
  },
  {
    id: "pumpkin_seeds",
    name: "Pumpkin Seeds (100g)",
    macros: {
      calories: 446,
      protein_g: 19,
      fat_g: 19,
      carbs_g: 54,
    },
    micros: {
      fiber_g: 18,
      sugar_g: 1.3,
      calcium_mg: 55,
      iron_mg: 3.3,
      magnesium_mg: 262,
      phosphorus_mg: 92,
      potassium_mg: 919,
      sodium_mg: 18,
      zinc_mg: 10,
      copper_mg: 0.69,
      manganese_mg: 0.5,
      selenium_mcg: 8.8,
      iodine_mcg: 2,
      saturated_fat_g: 3.6,
      monounsaturated_fat_g: 6.0,
      polyunsaturated_fat_g: 8.5,
      omega_3_g: 0.16,
      omega_6_g: 8.3,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.2,
      vitamin_b2_mg: 0.15,
      vitamin_b3_mg: 1.7,
      vitamin_b5_mg: 0.35,
      vitamin_b6_mg: 0.14,
      biotin_mcg: 6.4,
      folate_mcg: 58,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 9.5,
      vitamin_k_mcg: 0,
      choline_mg: 13,
      cholesterol_mg: 0,
    },
  },
  {
    id: "sunflower_seeds",
    name: "Sunflower Seeds (100g)",
    macros: {
      calories: 584,
      protein_g: 20.8,
      fat_g: 51.5,
      carbs_g: 20,
    },
    micros: {
      fiber_g: 8.6,
      sugar_g: 2.6,
      calcium_mg: 78,
      iron_mg: 5.3,
      magnesium_mg: 325,
      phosphorus_mg: 660,
      potassium_mg: 645,
      sodium_mg: 9,
      zinc_mg: 5,
      copper_mg: 1.8,
      manganese_mg: 2,
      selenium_mcg: 53,
      iodine_mcg: 3,
      saturated_fat_g: 4.5,
      monounsaturated_fat_g: 20.0,
      polyunsaturated_fat_g: 23.1,
      omega_3_g: 0.39,
      omega_6_g: 22.6,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 1.5,
      vitamin_b2_mg: 0.86,
      vitamin_b3_mg: 8.3,
      vitamin_b5_mg: 1.3,
      vitamin_b6_mg: 1.3,
      biotin_mcg: 97,
      folate_mcg: 227,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 1.5,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 35,
      vitamin_k_mcg: 0,
      choline_mg: 55,
      cholesterol_mg: 0,
    },
  },
  {
    id: "hemp_seeds",
    name: "Hemp Seeds (100g)",
    macros: {
      calories: 553,
      protein_g: 31.6,
      fat_g: 48.8,
      carbs_g: 8.7,
    },
    micros: {
      fiber_g: 4,
      sugar_g: 1.5,
      calcium_mg: 70,
      iron_mg: 8,
      magnesium_mg: 700,
      phosphorus_mg: 1650,
      potassium_mg: 1200,
      sodium_mg: 5,
      zinc_mg: 9.9,
      copper_mg: 1.6,
      manganese_mg: 7.6,
      selenium_mcg: 56,
      iodine_mcg: 5,
      saturated_fat_g: 4.6,
      monounsaturated_fat_g: 12.3,
      polyunsaturated_fat_g: 30.8,
      omega_3_g: 12.3,
      omega_6_g: 18.5,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 1.3,
      vitamin_b2_mg: 0.11,
      vitamin_b3_mg: 1.6,
      vitamin_b5_mg: 1.2,
      vitamin_b6_mg: 0.6,
      biotin_mcg: 71,
      folate_mcg: 110,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 1,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 1,
      vitamin_k_mcg: 0,
      choline_mg: 70,
      cholesterol_mg: 0,
    },
  },
  {
    id: "ghee",
    name: "Ghee (clarified butter, 100g)",
    macros: {
      calories: 876,
      protein_g: 0,
      fat_g: 99.8,
      carbs_g: 0,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 0,
      calcium_mg: 5,
      iron_mg: 0.2,
      magnesium_mg: 0,
      phosphorus_mg: 4,
      potassium_mg: 5,
      sodium_mg: 21,
      zinc_mg: 0.07,
      copper_mg: 0.001,
      manganese_mg: 0,
      selenium_mcg: 0.8,
      iodine_mcg: 5,
      saturated_fat_g: 62.4,
      monounsaturated_fat_g: 28.7,
      polyunsaturated_fat_g: 3.7,
      omega_3_g: 0.5,
      omega_6_g: 3.2,
      vitamin_a_mcg: 3069,
      vitamin_b1_mg: 0,
      vitamin_b2_mg: 0,
      vitamin_b3_mg: 0,
      vitamin_b5_mg: 0.04,
      vitamin_b6_mg: 0,
      biotin_mcg: 0,
      folate_mcg: 0,
      vitamin_b12_mcg: 0.23,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 1.3,
      vitamin_e_mg: 2.8,
      vitamin_k_mcg: 8.6,
      choline_mg: 5,
      cholesterol_mg: 256,
    },
  },
  {
    id: "mustard_oil",
    name: "Mustard Oil (100g)",
    macros: {
      calories: 884,
      protein_g: 0,
      fat_g: 100,
      carbs_g: 0,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 0,
      calcium_mg: 0,
      iron_mg: 0,
      magnesium_mg: 0,
      phosphorus_mg: 0,
      potassium_mg: 0,
      sodium_mg: 0,
      zinc_mg: 0,
      copper_mg: 0,
      manganese_mg: 0,
      selenium_mcg: 0,
      iodine_mcg: 0,
      saturated_fat_g: 12,
      monounsaturated_fat_g: 59,
      polyunsaturated_fat_g: 21,
      omega_3_g: 8.9,
      omega_6_g: 12,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0,
      vitamin_b2_mg: 0,
      vitamin_b3_mg: 0,
      vitamin_b5_mg: 0,
      vitamin_b6_mg: 0,
      biotin_mcg: 0,
      folate_mcg: 0,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.4,
      vitamin_k_mcg: 0,
      choline_mg: 0,
      cholesterol_mg: 0,
    },
  },
  {
    id: "rice",
    name: "Rice (white, dry, 100g)",
    macros: {
      calories: 365,
      protein_g: 7.1,
      fat_g: 0.7,
      carbs_g: 80,
    },
    micros: {
      fiber_g: 1.3,
      sugar_g: 0.1,
      calcium_mg: 28,
      iron_mg: 1.2,
      magnesium_mg: 25,
      phosphorus_mg: 150,
      potassium_mg: 115,
      sodium_mg: 9,
      zinc_mg: 1.1,
      copper_mg: 0.2,
      manganese_mg: 1.1,
      selenium_mcg: 15,
      iodine_mcg: 3,
      saturated_fat_g: 0.2,
      monounsaturated_fat_g: 0.2,
      polyunsaturated_fat_g: 0.2,
      omega_3_g: 0.01,
      omega_6_g: 0.2,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.07,
      vitamin_b2_mg: 0.03,
      vitamin_b3_mg: 1.6,
      vitamin_b5_mg: 1.0,
      vitamin_b6_mg: 0.12,
      biotin_mcg: 2,
      folate_mcg: 8,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.1,
      vitamin_k_mcg: 0,
      choline_mg: 3,
      cholesterol_mg: 0,
    },
  },
  {
    id: "rajma",
    name: "Rajma (kidney beans, dry, 100g)",
    macros: {
      calories: 337,
      protein_g: 23,
      fat_g: 1.0,
      carbs_g: 61,
    },
    micros: {
      fiber_g: 15,
      sugar_g: 2,
      calcium_mg: 83,
      iron_mg: 7,
      magnesium_mg: 138,
      phosphorus_mg: 406,
      potassium_mg: 1359,
      sodium_mg: 12,
      zinc_mg: 3,
      copper_mg: 0.75,
      manganese_mg: 1.0,
      selenium_mcg: 3,
      iodine_mcg: 6,
      saturated_fat_g: 0.1,
      monounsaturated_fat_g: 0.1,
      polyunsaturated_fat_g: 0.5,
      omega_3_g: 0.05,
      omega_6_g: 0.4,
      vitamin_a_mcg: 6,
      vitamin_b1_mg: 0.55,
      vitamin_b2_mg: 0.2,
      vitamin_b3_mg: 2.4,
      vitamin_b5_mg: 0.8,
      vitamin_b6_mg: 0.36,
      biotin_mcg: 38,
      folate_mcg: 394,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 4,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.2,
      vitamin_k_mcg: 0,
      choline_mg: 29,
      cholesterol_mg: 0,
    },
  },
  {
    id: "chickpeas",
    name: "Chickpeas (dry, 100g)",
    macros: {
      calories: 378,
      protein_g: 20,
      fat_g: 6,
      carbs_g: 63,
    },
    micros: {
      fiber_g: 12,
      sugar_g: 11,
      calcium_mg: 57,
      iron_mg: 4.3,
      magnesium_mg: 79,
      phosphorus_mg: 252,
      potassium_mg: 718,
      sodium_mg: 24,
      zinc_mg: 2.8,
      copper_mg: 0.66,
      manganese_mg: 1.21,
      selenium_mcg: 8,
      iodine_mcg: 6,
      saturated_fat_g: 0.6,
      monounsaturated_fat_g: 1.3,
      polyunsaturated_fat_g: 2.7,
      omega_3_g: 0.09,
      omega_6_g: 2.6,
      vitamin_a_mcg: 44,
      vitamin_b1_mg: 0.48,
      vitamin_b2_mg: 0.15,
      vitamin_b3_mg: 1.5,
      vitamin_b5_mg: 1.7,
      vitamin_b6_mg: 0.54,
      biotin_mcg: 48,
      folate_mcg: 557,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 4,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.8,
      vitamin_k_mcg: 9,
      choline_mg: 100,
      cholesterol_mg: 0,
    },
  },
  {
    id: "chicken",
    name: "Chicken Breast (cooked, 100g)",
    macros: {
      calories: 165,
      protein_g: 31,
      fat_g: 3.6,
      carbs_g: 0,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 0,
      calcium_mg: 12,
      iron_mg: 1,
      magnesium_mg: 29,
      phosphorus_mg: 222,
      potassium_mg: 256,
      sodium_mg: 74,
      zinc_mg: 1,
      copper_mg: 0.05,
      manganese_mg: 0.01,
      selenium_mcg: 22,
      iodine_mcg: 38,
      saturated_fat_g: 1.0,
      monounsaturated_fat_g: 1.4,
      polyunsaturated_fat_g: 0.7,
      omega_3_g: 0.03,
      omega_6_g: 0.6,
      vitamin_a_mcg: 6,
      vitamin_b1_mg: 0.05,
      vitamin_b2_mg: 0.1,
      vitamin_b3_mg: 14.8,
      vitamin_b5_mg: 1.0,
      vitamin_b6_mg: 0.6,
      biotin_mcg: 6,
      folate_mcg: 3,
      vitamin_b12_mcg: 0.3,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 0.1,
      vitamin_e_mg: 0.2,
      vitamin_k_mcg: 0,
      choline_mg: 85,
      cholesterol_mg: 85,
    },
  },
  {
    id: "apple",
    name: "Apple (raw, 100g)",
    macros: {
      calories: 52,
      protein_g: 0.3,
      fat_g: 0.2,
      carbs_g: 14,
    },
    micros: {
      fiber_g: 2.4,
      sugar_g: 10,
      calcium_mg: 6,
      iron_mg: 0.1,
      magnesium_mg: 5,
      phosphorus_mg: 11,
      potassium_mg: 107,
      sodium_mg: 1,
      zinc_mg: 0.04,
      copper_mg: 0.03,
      manganese_mg: 0.04,
      selenium_mcg: 0,
      iodine_mcg: 2,
      saturated_fat_g: 0.03,
      monounsaturated_fat_g: 0.01,
      polyunsaturated_fat_g: 0.05,
      omega_3_g: 0,
      omega_6_g: 0.05,
      vitamin_a_mcg: 5,
      vitamin_b1_mg: 0.02,
      vitamin_b2_mg: 0.03,
      vitamin_b3_mg: 0.1,
      vitamin_b5_mg: 0.11,
      vitamin_b6_mg: 0.04,
      biotin_mcg: 0.3,
      folate_mcg: 3,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 4.6,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.18,
      vitamin_k_mcg: 2.2,
      choline_mg: 3.4,
      cholesterol_mg: 0,
    },
  },
  {
    id: "banana",
    name: "Banana (raw, 100g)",
    macros: {
      calories: 89,
      protein_g: 1.1,
      fat_g: 0.3,
      carbs_g: 23,
    },
    micros: {
      fiber_g: 2.6,
      sugar_g: 12,
      calcium_mg: 5,
      iron_mg: 0.3,
      magnesium_mg: 27,
      phosphorus_mg: 22,
      potassium_mg: 358,
      sodium_mg: 1,
      zinc_mg: 0.15,
      copper_mg: 0.11,
      manganese_mg: 0.27,
      selenium_mcg: 1,
      iodine_mcg: 2,
      saturated_fat_g: 0.1,
      monounsaturated_fat_g: 0.03,
      polyunsaturated_fat_g: 0.07,
      omega_3_g: 0.01,
      omega_6_g: 0.06,
      vitamin_a_mcg: 3,
      vitamin_b1_mg: 0.03,
      vitamin_b2_mg: 0.07,
      vitamin_b3_mg: 0.67,
      vitamin_b5_mg: 0.33,
      vitamin_b6_mg: 0.37,
      biotin_mcg: 1,
      folate_mcg: 25,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 8.7,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.1,
      vitamin_k_mcg: 0.5,
      choline_mg: 9.6,
      cholesterol_mg: 0,
    },
  },
  {
    id: "cashews",
    name: "Cashews (dry, 100g)",
    macros: {
      calories: 553,
      protein_g: 18.2,
      fat_g: 43.8,
      carbs_g: 30.2,
    },
    micros: {
      fiber_g: 3.3,
      sugar_g: 5.9,
      calcium_mg: 37,
      iron_mg: 6.68,
      magnesium_mg: 292,
      phosphorus_mg: 593,
      potassium_mg: 660,
      sodium_mg: 10,
      zinc_mg: 5.8,
      copper_mg: 2.2,
      manganese_mg: 1.7,
      selenium_mcg: 19,
      iodine_mcg: 2,
      saturated_fat_g: 8.6,
      monounsaturated_fat_g: 23.8,
      polyunsaturated_fat_g: 7.8,
      omega_3_g: 0.06,
      omega_6_g: 7.7,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.42,
      vitamin_b2_mg: 0.22,
      vitamin_b3_mg: 1.9,
      vitamin_b5_mg: 0.9,
      vitamin_b6_mg: 0.42,
      biotin_mcg: 48,
      folate_mcg: 25,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 0.5,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.9,
      vitamin_k_mcg: 0,
      choline_mg: 15,
      cholesterol_mg: 0,
    },
  },
  {
    id: "raisins",
    name: "Raisins (100g)",
    macros: {
      calories: 299,
      protein_g: 3.1,
      fat_g: 0.5,
      carbs_g: 79,
    },
    micros: {
      fiber_g: 3.7,
      sugar_g: 59,
      calcium_mg: 50,
      iron_mg: 1.9,
      magnesium_mg: 32,
      phosphorus_mg: 101,
      potassium_mg: 749,
      sodium_mg: 11,
      zinc_mg: 0.22,
      copper_mg: 0.32,
      manganese_mg: 0.3,
      selenium_mcg: 0.5,
      iodine_mcg: 3,
      saturated_fat_g: 0.1,
      monounsaturated_fat_g: 0.05,
      polyunsaturated_fat_g: 0.17,
      omega_3_g: 0,
      omega_6_g: 0.17,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.11,
      vitamin_b2_mg: 0.09,
      vitamin_b3_mg: 0.8,
      vitamin_b5_mg: 0.1,
      vitamin_b6_mg: 0.07,
      biotin_mcg: 1.2,
      folate_mcg: 5,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 2.3,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.12,
      vitamin_k_mcg: 3.5,
      choline_mg: 14,
      cholesterol_mg: 0,
    },
  },
  {
    id: "spinach",
    name: "Spinach (raw, 100g)",
    macros: {
      calories: 23,
      protein_g: 2.9,
      fat_g: 0.4,
      carbs_g: 3.6,
    },
    micros: {
      fiber_g: 2.2,
      sugar_g: 0.4,
      calcium_mg: 99,
      iron_mg: 2.7,
      magnesium_mg: 79,
      phosphorus_mg: 49,
      potassium_mg: 558,
      sodium_mg: 79,
      zinc_mg: 0.5,
      copper_mg: 0.1,
      manganese_mg: 0.9,
      selenium_mcg: 1,
      iodine_mcg: 3,
      saturated_fat_g: 0.06,
      monounsaturated_fat_g: 0.04,
      polyunsaturated_fat_g: 0.16,
      omega_3_g: 0.14,
      omega_6_g: 0.02,
      vitamin_a_mcg: 469,
      vitamin_b1_mg: 0.08,
      vitamin_b2_mg: 0.19,
      vitamin_b3_mg: 0.7,
      vitamin_b5_mg: 0.07,
      vitamin_b6_mg: 0.19,
      biotin_mcg: 0.9,
      folate_mcg: 194,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 28.1,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 2.0,
      vitamin_k_mcg: 482.9,
      choline_mg: 19,
      cholesterol_mg: 0,
    },
  },
  {
    id: "amla",
    name: "Amla (Indian gooseberry, raw, 100g)",
    macros: {
      calories: 44,
      protein_g: 0.9,
      carbs_g: 10.2,
      fat_g: 0.6,
    },
    micros: {
      fiber_g: 4.3,
      sugar_g: 4.4,
      calcium_mg: 25,
      iron_mg: 0.9,
      magnesium_mg: 10,
      phosphorus_mg: 21,
      potassium_mg: 198,
      sodium_mg: 13,
      zinc_mg: 0.12,
      copper_mg: 0.1,
      manganese_mg: 0.1,
      selenium_mcg: 0.6,
      iodine_mcg: 2,
      saturated_fat_g: 0.05,
      monounsaturated_fat_g: 0.08,
      polyunsaturated_fat_g: 0.34,
      omega_3_g: 0.048,
      omega_6_g: 0.3,
      vitamin_a_mcg: 31,
      vitamin_b1_mg: 0.04,
      vitamin_b2_mg: 0.03,
      vitamin_b3_mg: 0.3,
      vitamin_b5_mg: 0.25,
      vitamin_b6_mg: 0.06,
      biotin_mcg: 0.2,
      folate_mcg: 6,
      vitamin_b12_mcg: 0,
      vitamin_c_mg: 478,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.16,
      vitamin_k_mcg: 1.6,
      choline_mg: 4,
      cholesterol_mg: 0,
    },
  },
  {
    id: "nori",
    name: "Nori (seaweed, dried, 100g)",
    macros: {
      calories: 333,
      protein_g: 40,
      fat_g: 7,
      carbs_g: 43,
    },
    micros: {
      fiber_g: 35,
      sugar_g: 0,
      calcium_mg: 430,
      iron_mg: 8,
      magnesium_mg: 110,
      phosphorus_mg: 340,
      potassium_mg: 1200,
      sodium_mg: 4200,
      zinc_mg: 1.2,
      copper_mg: 0.1,
      manganese_mg: 0.8,
      selenium_mcg: 200,
      iodine_mcg: 1500,
      saturated_fat_g: 1.3,
      monounsaturated_fat_g: 0.9,
      polyunsaturated_fat_g: 3.6,
      omega_3_g: 0.8,
      omega_6_g: 2.8,
      vitamin_a_mcg: 900,
      vitamin_b1_mg: 0.8,
      vitamin_b2_mg: 0.5,
      vitamin_b3_mg: 8,
      vitamin_b5_mg: 0.5,
      vitamin_b6_mg: 1.0,
      biotin_mcg: 200,
      folate_mcg: 750,
      vitamin_b12_mcg: 50,
      vitamin_c_mg: 15,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 4,
      vitamin_k_mcg: 0,
      choline_mg: 200,
      cholesterol_mg: 0,
    },
  },
  {
    id: "cod",
    name: "Cod (cooked, 100g)",
    macros: {
      calories: 82,
      protein_g: 18,
      fat_g: 0.7,
      carbs_g: 0,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 0,
      calcium_mg: 16,
      iron_mg: 0.4,
      magnesium_mg: 32,
      phosphorus_mg: 200,
      potassium_mg: 413,
      sodium_mg: 77,
      zinc_mg: 0.5,
      copper_mg: 0.05,
      manganese_mg: 0.01,
      selenium_mcg: 36,
      iodine_mcg: 99,
      saturated_fat_g: 0.1,
      monounsaturated_fat_g: 0.1,
      polyunsaturated_fat_g: 0.3,
      omega_3_g: 0.24,
      omega_6_g: 0.05,
      vitamin_a_mcg: 12,
      vitamin_b1_mg: 0.05,
      vitamin_b2_mg: 0.08,
      vitamin_b3_mg: 2.1,
      vitamin_b5_mg: 0.6,
      vitamin_b6_mg: 0.12,
      biotin_mcg: 0,
      folate_mcg: 12,
      vitamin_b12_mcg: 0.9,
      vitamin_c_mg: 0,
      vitamin_d_mcg: 10,
      vitamin_e_mg: 0,
      vitamin_k_mcg: 0,
      choline_mg: 65,
      cholesterol_mg: 43,
    },
  },
  {
    id: "oyster",
    name: "Oyster (cooked, 100g)",
    macros: {
      calories: 81,
      protein_g: 14,
      fat_g: 2.3,
      carbs_g: 4.7,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 0,
      calcium_mg: 101,
      iron_mg: 5.7,
      magnesium_mg: 34,
      phosphorus_mg: 193,
      potassium_mg: 168,
      sodium_mg: 92,
      zinc_mg: 16,
      copper_mg: 3.9,
      manganese_mg: 0.6,
      selenium_mcg: 63,
      iodine_mcg: 160,
      saturated_fat_g: 0.6,
      monounsaturated_fat_g: 0.4,
      polyunsaturated_fat_g: 0.9,
      omega_3_g: 0.5,
      omega_6_g: 0.4,
      vitamin_a_mcg: 73,
      vitamin_b1_mg: 0.1,
      vitamin_b2_mg: 0.17,
      vitamin_b3_mg: 1.6,
      vitamin_b5_mg: 0.9,
      vitamin_b6_mg: 0.05,
      biotin_mcg: 0,
      folate_mcg: 5,
      vitamin_b12_mcg: 16,
      vitamin_c_mg: 3,
      vitamin_d_mcg: 8,
      vitamin_e_mg: 0,
      vitamin_k_mcg: 0,
      choline_mg: 65,
      cholesterol_mg: 50,
    },
  },
  {
    id: "yogurt",
    name: "Yogurt (plain, full-fat, 100g)",
    macros: {
      calories: 61,
      protein_g: 3.5,
      fat_g: 3.3,
      carbs_g: 4.7,
    },
    micros: {
      fiber_g: 0,
      sugar_g: 4.4,
      calcium_mg: 121,
      iron_mg: 0.1,
      magnesium_mg: 12,
      phosphorus_mg: 95,
      potassium_mg: 155,
      sodium_mg: 75,
      zinc_mg: 0.6,
      copper_mg: 0.01,
      manganese_mg: 0.003,
      selenium_mcg: 4,
      iodine_mcg: 32,
      saturated_fat_g: 2.1,
      monounsaturated_fat_g: 0.8,
      polyunsaturated_fat_g: 0.2,
      omega_3_g: 0.04,
      omega_6_g: 0.1,
      vitamin_a_mcg: 32,
      vitamin_b1_mg: 0.03,
      vitamin_b2_mg: 0.17,
      vitamin_b3_mg: 0.09,
      vitamin_b5_mg: 0.36,
      vitamin_b6_mg: 0.06,
      biotin_mcg: 2,
      folate_mcg: 7,
      vitamin_b12_mcg: 0.37,
      vitamin_c_mg: 0.6,
      vitamin_d_mcg: 0.5,
      vitamin_e_mg: 0.06,
      vitamin_k_mcg: 0.2,
      choline_mg: 15,
      cholesterol_mg: 11,
    },
  },
];

export const dailyRequirements: Total = {
  macros: {
    calories: 2000,
    protein_g: 50,
    carbs_g: 275,
    fat_g: 65,
  },
  micros: {
    calcium_mg: 1000,
    iron_mg: 18,
    zinc_mg: 11,
    magnesium_mg: 400,
    phosphorus_mg: 700,
    potassium_mg: 4700,
    sodium_mg: 1500,
    copper_mg: 0.9,
    manganese_mg: 2.3,
    selenium_mcg: 55,
    iodine_mcg: 150,

    vitamin_a_mcg: 900,
    vitamin_a_iu: 3000,
    vitamin_d_mcg: 15,
    vitamin_e_mg: 15,
    vitamin_k_mcg: 120,
    beta_carotene_mcg: 3600,

    vitamin_b1_mg: 1.2,
    vitamin_b2_mg: 1.3,
    riboflavin_mg: 1.3,
    vitamin_b3_mg: 16,
    niacin_mg: 16,
    vitamin_b5_mg: 5,
    vitamin_b6_mg: 1.3,
    biotin_mcg: 30,
    vitamin_b7_mcg: 30,
    folate_mcg: 400,
    vitamin_b9_mcg: 400,
    vitamin_b12_mcg: 2.4,

    vitamin_c_mg: 90,

    fiber_g: 28,
    sugar_g: 25,
    saturated_fat_g: 20,
    monounsaturated_fat_g: 35,
    polyunsaturated_fat_g: 11,
    omega_3_g: 1.6,
    omega_6_g: 17,
    cholesterol_mg: 300,

    choline_mg: 550,
  },
} as const;
