import type { Micros, Macros } from "@/types/globaltypes";

export const micros: (keyof Micros)[] = [
  "fiber_g",
  "sugar_g",
  "saturated_fat_g",
  "monounsaturated_fat_g",
  "polyunsaturated_fat_g",
  "cholesterol_mg",
  "omega_3_g",
  "calcium_mg",
  "iron_mg",
  "magnesium_mg",
  "phosphorus_mg",
  "potassium_mg",
  "sodium_mg",
  "zinc_mg",
  "copper_mg",
  "manganese_mg",
  "selenium_mcg",
  "vitamin_a_mcg",
  "vitamin_a_iu",
  "vitamin_c_mg",
  "vitamin_d_mcg",
  "vitamin_b2_mg",
"vitamin_b5_mg",
"vitamin_b7_mcg",
  "vitamin_e_mg",
  "vitamin_k_mcg",
  "vitamin_b1_mg",
  "vitamin_b3_mg",
  "vitamin_b6_mg",
  "vitamin_b12_mcg",
  "riboflavin_mg",
  "folate_mcg",
  "choline_mg",
  "niacin_mg",
  
];
export const macros: (keyof Macros)[] = [
  "calories",
  "protein_g",
  "fat_g",
  "carbs_g",
] 
